### PR TITLE
fix: Automatically update app version of Helm chart

### PR DESCRIPTION
**Pull request by tomkerkhove**
Relates to https://github.com/benc-uk/kubeview/issues/42

Happy to re-use the same version for the chart if you prefer that, but you might want to use different versions.

### CODE REVIEW

**Comment by benc-uk** [comment]
Thanks Tom, just spotted this, not sure why I was setting version to 0.0.0 probably trying to be too clever!
I've ended up fixing this in 93aa0cc before I spotted your PR, lol sorry!

**Comment by tomkerkhove** [comment]
No problem @benc-uk! But you're not assigning a version so it will just use whatever is in the YAML, is that what you're looking for? Because the app version should be hardcoded then as well, but it's not respecting the tag that was created or am I missing something?

**Comment by benc-uk** [comment]
yeah I should update the version in Chart.yaml before doing a release, but I forget this time

There's also the matter of updating the index.yaml etc, and I now need the .tgz file committed to the repo since artifacthub is pointed at this repo as a source.

Basically all the fiddly manual release stuff I've not got round to automating in an actions yet :)

**Comment by tomkerkhove** [comment]
Oh you are not alone in this :) I've created a note to remind myself: https://github.com/kedacore/charts/blob/master/CONTRIBUTING.md#shipping-a-new-version

**Comment by benc-uk** [comment]
Hah! Glad it's not just me :) I should go all in with GitHub actions and automate the lot, but it's difficult to "test in production" now the repo is live and has people subscribed to it, creating releases to test things is going to generate spam notifications.

I should fork the repo and test it all there, but just haven't had time

**Comment by tomkerkhove** [comment]
That would make a good blog post, but I feel your pain :D

**Pull request closed without merging**
